version: '3.8'
services:
  ors-app-gcc-map:
    build:
      context: ./
    container_name: ors-app-gcc-map
    ports:
      - "8080:8082"
    volumes:
      - ./ors-docker/elevation_cache:/home/ors/elevation_cache
      - ./ors-docker/logs:/home/ors/logs
      - ./data/mount/ors/graphs:/home/ors/graphs
      - ./data/config:/home/ors/config
      - ./data/files:/home/ors/files
    environment:
      REBUILD_GRAPHS: False
      ORS_CONFIG_LOCATION: /home/ors/config/gcc-states-ors-config.yml
      XMS: 1g
      XMX: 2g
      ors.engine.profiles.car.enabled: true
